server:
  port: 8080
spring:
  application:
    name: todo-resource-server
  jpa:
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-todo:9000